/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        "colors": {
                "on-surface": "#363C48",
                "inverse-on-surface": "#f0f1f1",
                "primary-fixed-dim": "#ffb3ac",
                "inverse-surface": "#2f3131",
                "primary-fixed": "#ffdad6",
                "surface-container-high": "#e8e8e8",
                "tertiary-container": "#00799c",
                "outline-variant": "#e4beba",
                "on-tertiary": "#ffffff",
                "outline": "#E0E0E0",
                "on-surface-variant": "#5b403d",
                "on-error": "#ffffff",
                "background": "#ffffff",
                "error": "#ba1a1a",
                "surface-container": "#F8F9FA",
                "surface-container-lowest": "#ffffff",
                "primary-container": "#ffc1bc",
                "on-primary-fixed-variant": "#930010",
                "surface-tint": "#ba1a20",
                "tertiary-fixed-dim": "#7bd1f8",
                "primary": "#E52327",
                "on-primary-container": "#3A0004",
                "surface-bright": "#ffffff",
                "tertiary": "#005f7b",
                "tertiary-fixed": "#bee9ff",
                "on-secondary-fixed": "#001c3a",
                "error-container": "#ffdad6",
                "on-background": "#363C48",
                "on-primary-fixed": "#410003",
                "surface-variant": "#e2e2e2",
                "secondary-fixed-dim": "#a5c8ff",
                "surface-container-highest": "#e2e2e2",
                "success-eco": "#2E7D32",
                "surface-dim": "#dadada",
                "on-primary": "#ffffff",
                "on-tertiary-container": "#e9f7ff",
                "on-secondary": "#ffffff",
                "secondary": "#363C48",
                "inverse-primary": "#ffb3ac",
                "on-secondary-container": "#003567",
                "surface-container-low": "#f3f3f4",
                "secondary-fixed": "#d4e3ff",
                "on-secondary-fixed-variant": "#004786",
                "on-tertiary-fixed": "#001f2a",
                "secondary-container": "#54a0fe",
                "on-tertiary-fixed-variant": "#004d65",
                "surface": "#ffffff",
                "on-error-container": "#93000a"
        },
        "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
        },
        "spacing": {
                "gutter": "24px",
                "base": "8px",
                "margin-mobile": "16px",
                "section-gap": "120px",
                "margin-desktop": "64px"
        },
        "fontFamily": {
                "label-sm": ["Inter"],
                "headline-md": ["Montserrat"],
                "body-md": ["Inter"],
                "headline-lg-mobile": ["Montserrat"],
                "display-lg": ["Montserrat"],
                "label-md": ["Inter"],
                "body-lg": ["Inter"],
                "headline-lg": ["Montserrat"]
        },
        "fontSize": {
                "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "700" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "30px", "fontWeight": "400" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
        }
      },
    },
    plugins: [],
}